package com.loyalty.marketplace.merchants.constants;

public enum MerchantConstants {

	MERCHANT_DEFAULT_STATUS("Inactive"),
	MERCHANT_ACTIVE_STATUS("Active"),
	DISCOUNT_BILLING_CODE("DISCOUNT"),
	POINTS_TYPE_RATE("POINTS"),
	AED_TYPE_RATE("AED"),
	SEMI_COLON(" : "),
	CHANNELID_WEB("WEB"),
	CHANNELID_ADMIN("ADMIN_PORTAL"),
	CATEGORY_ALL("ALL"),
	FILTER_FLAG_KEYWORD("KEYWORD"),
	FILTER_EARN("EARN"),
	FILTER_CASH("CASH"),
	IMAGE_CATEGORY_MERCHANT_OFFER("MerchantOffer"),
	
	NOTIFICATION_LANGUAGE_EN("en"),
	NOTIFICATION_LANGUAGE_AR("ar"),
	EMAIL_MERCHANT_STATUS_UPDATE_FIRST_NAME("FIRST_NAME"),
	EMAIL_MERCHANT_STATUS_UPDATE_MERCHANT_CODE("MERCHANTCODE"),
	EMAIL_MERCHANT_STATUS_UPDATE_STATUS("STATUS"),
	EMAIL_MERCHANT_STATUS_UPDATE_TEMPLATE_ID("530972684"),
	EMAIL_MERCHANT_STATUS_UPDATE_NOTIFICATION_ID("10"),
	EMAIL_MERCHANT_STATUS_UPDATE_NOTIFICATION_CODE("00");

	private final String constant;

	MerchantConstants(String constant) {
		this.constant = constant;
	}

	public String get() {
		return this.constant;
	}

}
