package com.responsetek.rt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2021-06-28T11:31:45.420+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://rt.responsetek.com/", name = "RTInviteSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RTInviteSoap {

    @WebMethod(operationName = "EnqueueInvites", action = "http://rt.responsetek.com/EnqueueInvites")
    @RequestWrapper(localName = "EnqueueInvites", targetNamespace = "http://rt.responsetek.com/", className = "com.responsetek.rt.EnqueueInvites")
    @ResponseWrapper(localName = "EnqueueInvitesResponse", targetNamespace = "http://rt.responsetek.com/", className = "com.responsetek.rt.EnqueueInvitesResponse")
    @WebResult(name = "EnqueueInvitesResult", targetNamespace = "http://rt.responsetek.com/")
    public java.lang.String enqueueInvites(
        @WebParam(name = "message", targetNamespace = "http://rt.responsetek.com/")
        com.responsetek.rt.RTXmlMessage message
    );

    @WebMethod(operationName = "GetProcessStatus", action = "http://rt.responsetek.com/GetProcessStatus")
    @RequestWrapper(localName = "GetProcessStatus", targetNamespace = "http://rt.responsetek.com/", className = "com.responsetek.rt.GetProcessStatus")
    @ResponseWrapper(localName = "GetProcessStatusResponse", targetNamespace = "http://rt.responsetek.com/", className = "com.responsetek.rt.GetProcessStatusResponse")
    @WebResult(name = "GetProcessStatusResult", targetNamespace = "http://rt.responsetek.com/")
    public java.lang.String getProcessStatus(
        @WebParam(name = "token", targetNamespace = "http://rt.responsetek.com/")
        com.responsetek.rt.RTToken token
    );
}
