package com.responsetek.rt;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2021-06-28T11:31:45.432+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://rt.responsetek.com/", name = "RTInviteHttpGet")
@XmlSeeAlso({ObjectFactory.class})
public interface RTInviteHttpGet {
}
