
package ae.etisalat.middleware.serviceordermgmt_cud;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-04-03T16:13:42.060+05:30
 * Generated source version: 3.2.4
 */

@WebFault(name = "AckMessage", targetNamespace = "http://www.etisalat.ae/Middleware/SharedResources/Common/AckMessage.xsd")
public class Error extends Exception {

    private ae.etisalat.middleware.sharedresources.common.ackmessage.AckMessage ackMessage;

    public Error() {
        super();
    }

    public Error(String message) {
        super(message);
    }

    public Error(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Error(String message, ae.etisalat.middleware.sharedresources.common.ackmessage.AckMessage ackMessage) {
        super(message);
        this.ackMessage = ackMessage;
    }

    public Error(String message, ae.etisalat.middleware.sharedresources.common.ackmessage.AckMessage ackMessage, java.lang.Throwable cause) {
        super(message, cause);
        this.ackMessage = ackMessage;
    }

    public ae.etisalat.middleware.sharedresources.common.ackmessage.AckMessage getFaultInfo() {
        return this.ackMessage;
    }
}
