package ae.etisalat.middleware.serviceordermgmt_cud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-04-03T16:13:42.117+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD", name = "ServiceOrderMgmt_CUD")
@XmlSeeAlso({ae.etisalat.middleware.serviceordermgmt_cud.managegamestreamsubscriptionrequest.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.updatesaasaccountresponse.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.activatebodresponse.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.ypayserviceorderrequest.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.ypayserviceorderresponse.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.provisionsaasservicerequest.ObjectFactory.class, ae.etisalat.middleware.sharedresources.common.ackmessage.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.activatebodrequest.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.unsubscribeservicesresponse.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.provisionsaasserviceresponse.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.subscribeservicesrequest.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.appledepenrollmentrequest.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.unsubscribeservicesrequest.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.provisionserviceorderrequest.ObjectFactory.class, ae.etisalat.middleware.sharedresources.common.applicationheader.ObjectFactory.class, ae.etisalat.middleware.sharedresources.common.common.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.appledepenrollmentrespose.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.updatesaasaccountrequestrequest.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.provisionserviceorderresponse.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.subscribeservicesresponse.ObjectFactory.class, ae.etisalat.middleware.serviceordermgmt_cud.managegamestreamsubscriptionresponse.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceOrderMgmtCUD {

    @WebMethod(operationName = "OpUpdateSaaSAccount", action = "/Middleware/ServiceOrderMgmt_CUD/UpdateSaaSAccount")
    @WebResult(name = "UpdateSaaSAccountRequestResponse", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/UpdateSaaSAccountResponse.xsd", partName = "UpdateSaaSAccountResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.updatesaasaccountresponse.UpdateSaaSAccountRequestResponse opUpdateSaaSAccount(
        @WebParam(partName = "UpdateSaaSAccountRequest", name = "UpdateSaaSAccountRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/UpdateSaaSAccountRequestRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.updatesaasaccountrequestrequest.UpdateSaaSAccountRequest updateSaaSAccountRequest
    ) throws Error;

    @WebMethod(operationName = "OpProvisionServiceOrder", action = "/Middleware/ServiceOrderMgmt_CUD/ProvisionServiceOrder")
    @WebResult(name = "ProvisionServiceOrderResponse", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/ProvisionServiceOrderResponse.xsd", partName = "ProvisionServiceOrderResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.provisionserviceorderresponse.ProvisionServiceOrderResponse opProvisionServiceOrder(
        @WebParam(partName = "ProvisionServiceOrderRequest", name = "ProvisionServiceOrderRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/ProvisionServiceOrderRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.provisionserviceorderrequest.ProvisionServiceOrderRequest provisionServiceOrderRequest
    ) throws Error;

    @WebMethod(operationName = "OpUnsubscribeServices", action = "/Middleware/ServiceOrderMgmt_CUD/UnsubscribeServices")
    @WebResult(name = "UnsubscribeServicesResponse", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/UnsubscribeServicesResponse.xsd", partName = "UnsubscribeServicesResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.unsubscribeservicesresponse.UnsubscribeServicesResponseType opUnsubscribeServices(
        @WebParam(partName = "UnsubscribeServicesRequest", name = "UnsubscribeServicesRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/UnsubscribeServicesRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.unsubscribeservicesrequest.UnsubscribeServicesRequestType unsubscribeServicesRequest
    ) throws Error;

    @WebMethod(operationName = "OpSubscribeServices", action = "/Middleware/ServiceOrderMgmt_CUD/SubscribeServices")
    @WebResult(name = "SubscribeServicesResponse", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/SubscribeServicesResponse.xsd", partName = "SubscribeServicesResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.subscribeservicesresponse.SubscribeServicesResponse opSubscribeServices(
        @WebParam(partName = "SubscribeServicesRequest", name = "SubscribeServicesRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/SubscribeServicesRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.subscribeservicesrequest.SubscribeServicesRequest subscribeServicesRequest
    ) throws Error;

    @WebMethod(operationName = "OpYPAYServiceOrder", action = "/Middleware/ServiceOrderMgmt_CUD/YPAYServiceOrder")
    @WebResult(name = "YPAYServiceOrderResponse", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/YPAYServiceOrderResponse.xsd", partName = "YPAYServiceOrderResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.ypayserviceorderresponse.YPAYServiceOrderResponse opYPAYServiceOrder(
        @WebParam(partName = "YPAYServiceOrderRequest", name = "YPAYServiceOrderRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/YPAYServiceOrderRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.ypayserviceorderrequest.YPAYServiceOrderRequest ypayServiceOrderRequest
    ) throws Error;

    @WebMethod(operationName = "OpProvisionSaaSService", action = "/Middleware/ServiceOrderMgmt_CUD/ProvisionSaaSService")
    @WebResult(name = "ProvisionSaaSServiceResponse", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/ProvisionSaaSServiceResponse.xsd", partName = "ProvisionSaaSServiceResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.provisionsaasserviceresponse.ProvisionSaaSServiceResponse opProvisionSaaSService(
        @WebParam(partName = "ProvisionSaaSServiceRequest", name = "ProvisionSaaSServiceRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/ProvisionSaaSServiceRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.provisionsaasservicerequest.ProvisionSaaSServiceRequest provisionSaaSServiceRequest
    ) throws Error;

    @WebMethod(operationName = "OpActivateBoD", action = "/Middleware/ServiceOrderMgmt_CUD/ActivateBoD")
    @WebResult(name = "ActivateBoDResponse", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/ActivateBoDResponse.xsd", partName = "ActivateBoDResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.activatebodresponse.ActivateBoDResponse opActivateBoD(
        @WebParam(partName = "ActivateBoDRequest", name = "ActivateBoDRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/ActivateBoDRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.activatebodrequest.ActivateBoDRequest activateBoDRequest
    ) throws Error;

    @WebMethod(operationName = "OpManageGameStreamSubscription", action = "/Middleware/ServiceOrderMgmt_CUD/ManageGameStreamSubscription")
    @WebResult(name = "ManageGameStreamSubscriptionResponse", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/ManageGameStreamSubscriptionResponse.xsd", partName = "ManageGameStreamSubscriptionResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.managegamestreamsubscriptionresponse.ManageGameStreamSubscriptionResponseType opManageGameStreamSubscription(
        @WebParam(partName = "ManageGameStreamSubscriptionRequest", name = "ManageGameStreamSubscriptionRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/ManageGameStreamSubscriptionRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.managegamestreamsubscriptionrequest.ManageGameStreamSubscriptionRequestType manageGameStreamSubscriptionRequest
    ) throws Error;

    @WebMethod(operationName = "OpAppleDEPEnrollment", action = "/Middleware/ServiceOrderMgmt_CUD/AppleDEPEnrollment")
    @WebResult(name = "AppleDEPEnrollmentRespose", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/AppleDEPEnrollmentRespose.xsd", partName = "AppleDEPEnrollmentResponse")
    public ae.etisalat.middleware.serviceordermgmt_cud.appledepenrollmentrespose.AppleDEPEnrollmentRespose opAppleDEPEnrollment(
        @WebParam(partName = "AppleDEPEnrollmentRequest", name = "AppleDEPEnrollmentRequest", targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD/AppleDEPEnrollmentRequest.xsd")
        ae.etisalat.middleware.serviceordermgmt_cud.appledepenrollmentrequest.AppleDEPEnrollmentRequest appleDEPEnrollmentRequest
    ) throws Error;
}
