package ae.etisalat.middleware.serviceordermgmt_cud;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-04-03T16:13:42.144+05:30
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ServiceOrderMgmt_CUD",
                  wsdlLocation = "http://tibcononprd.etisalat.corp.ae:9375/Middleware/ServiceOrderMgmt_CUD?wsdl",
                  targetNamespace = "http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD")
public class ServiceOrderMgmtCUD_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD", "ServiceOrderMgmt_CUD.serviceagent");
    public final static QName ServiceOrderMgmtCUDEndpoint = new QName("http://www.etisalat.ae/Middleware/ServiceOrderMgmt_CUD", "ServiceOrderMgmt_CUDEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://tibcononprd.etisalat.corp.ae:9375/Middleware/ServiceOrderMgmt_CUD?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceOrderMgmtCUD_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://tibcononprd.etisalat.corp.ae:9375/Middleware/ServiceOrderMgmt_CUD?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceOrderMgmtCUD_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceOrderMgmtCUD_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceOrderMgmtCUD_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiceOrderMgmtCUD_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiceOrderMgmtCUD_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceOrderMgmtCUD_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServiceOrderMgmtCUD
     */
    @WebEndpoint(name = "ServiceOrderMgmt_CUDEndpoint")
    public ServiceOrderMgmtCUD getServiceOrderMgmtCUDEndpoint() {
        return super.getPort(ServiceOrderMgmtCUDEndpoint, ServiceOrderMgmtCUD.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceOrderMgmtCUD
     */
    @WebEndpoint(name = "ServiceOrderMgmt_CUDEndpoint")
    public ServiceOrderMgmtCUD getServiceOrderMgmtCUDEndpoint(WebServiceFeature... features) {
        return super.getPort(ServiceOrderMgmtCUDEndpoint, ServiceOrderMgmtCUD.class, features);
    }

}
