package ae.etisalat.middleware.bwtemplate.webservicename;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-11-11T17:04:12.114+04:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "GenericPaymentService.serviceagent",
                  wsdlLocation = "http://localhost:9164/Middleware/GenericPaymentService?wsdl",
                  targetNamespace = "http://www.etisalat.ae/Middleware/BWTemplate/WebserviceName")
public class GenericPaymentServiceServiceagent extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.etisalat.ae/Middleware/BWTemplate/WebserviceName", "GenericPaymentService.serviceagent");
    public final static QName GenericPaymentServiceEndpoint1 = new QName("http://www.etisalat.ae/Middleware/BWTemplate/WebserviceName", "GenericPaymentServiceEndpoint1");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9164/Middleware/GenericPaymentService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GenericPaymentServiceServiceagent.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9164/Middleware/GenericPaymentService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GenericPaymentServiceServiceagent(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GenericPaymentServiceServiceagent(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericPaymentServiceServiceagent() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GenericPaymentServiceServiceagent(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GenericPaymentServiceServiceagent(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GenericPaymentServiceServiceagent(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GenericPaymentService
     */
    @WebEndpoint(name = "GenericPaymentServiceEndpoint1")
    public GenericPaymentService getGenericPaymentServiceEndpoint1() {
        return super.getPort(GenericPaymentServiceEndpoint1, GenericPaymentService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenericPaymentService
     */
    @WebEndpoint(name = "GenericPaymentServiceEndpoint1")
    public GenericPaymentService getGenericPaymentServiceEndpoint1(WebServiceFeature... features) {
        return super.getPort(GenericPaymentServiceEndpoint1, GenericPaymentService.class, features);
    }

}
