package ae.billingadapter.etisalat._1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-11-14T14:39:04.584+04:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", name = "BillingAdapterWS4")
@XmlSeeAlso({ae.billingadapter.etisalat._1.ObjectFactory.class})
public interface BillingAdapterWS4 {

    @WebMethod
    @RequestWrapper(localName = "isAmountInUserRange", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.IsAmountInUserRange")
    @ResponseWrapper(localName = "isAmountInUserRangeResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.IsAmountInUserRangeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean isAmountInUserRange(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "isAmountInUserRangeSpecialCase", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.IsAmountInUserRangeSpecialCase")
    @ResponseWrapper(localName = "isAmountInUserRangeSpecialCaseResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.IsAmountInUserRangeSpecialCaseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean isAmountInUserRangeSpecialCase(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "startCharge", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.StartCharge")
    @ResponseWrapper(localName = "startChargeResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.StartChargeResponse")
    @WebResult(name = "StartChargingResponse", targetNamespace = "")
    public ae.billingadapter.etisalat._1.StartChargingResponse startCharge(
        @WebParam(name = "StartChargeRequest", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0")
        ae.billingadapter.etisalat._1.StartChargingRequest startChargeRequest
    );

    @WebMethod
    @RequestWrapper(localName = "getIP", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.GetIP")
    @ResponseWrapper(localName = "getIPResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.GetIPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getIP();

    @WebMethod(action = "/BillingAdapter/continueCharge")
    @RequestWrapper(localName = "continueCharge", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.ContinueCharge")
    @ResponseWrapper(localName = "continueChargeResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.ContinueChargeResponse")
    @WebResult(name = "ContinueChargingResponse", targetNamespace = "")
    public ae.billingadapter.etisalat._1.ContinueChargingResponse continueCharge(
        @WebParam(name = "ContinueChargeRequest", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0")
        ae.billingadapter.etisalat._1.ContinueChargeRequest continueChargeRequest
    );

    @WebMethod(action = "/BillingAdapter/ChargeImmediate")
    @RequestWrapper(localName = "chargeImmediate", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.ChargeImmediate")
    @ResponseWrapper(localName = "chargeImmediateResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.ChargeImmediateResponse")
    @WebResult(name = "ChargeImmediatelyResponse", targetNamespace = "")
    public ae.billingadapter.etisalat._1.ChargeImmediatelyResponse chargeImmediate(
        @WebParam(name = "ChargeImmediateRequest", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0")
        ae.billingadapter.etisalat._1.ChargeImmediateRequest chargeImmediateRequest
    );

    @WebMethod
    @RequestWrapper(localName = "isAmountInRangeSpecialCase", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.IsAmountInRangeSpecialCase")
    @ResponseWrapper(localName = "isAmountInRangeSpecialCaseResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.IsAmountInRangeSpecialCaseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean isAmountInRangeSpecialCase(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.GetUserNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getUserName();

    @WebMethod
    @RequestWrapper(localName = "isAmountInRange", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.IsAmountInRange")
    @ResponseWrapper(localName = "isAmountInRangeResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.IsAmountInRangeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean isAmountInRange(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "stopCharge", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.StopCharge")
    @ResponseWrapper(localName = "stopChargeResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.StopChargeResponse")
    @WebResult(name = "StopChargingResponse", targetNamespace = "")
    public ae.billingadapter.etisalat._1.StopChargingResponse stopCharge(
        @WebParam(name = "StopChargRequest", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0")
        ae.billingadapter.etisalat._1.StopChargingRequest stopChargRequest
    );

    @WebMethod
    @RequestWrapper(localName = "refundImmediate", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.RefundImmediate")
    @ResponseWrapper(localName = "refundImmediateResponse", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0", className = "ae.billingadapter.etisalat._1.RefundImmediateResponse")
    @WebResult(name = "RefundImmediatelyResponse", targetNamespace = "")
    public ae.billingadapter.etisalat._1.RefundImmediatelyResponse refundImmediate(
        @WebParam(name = "RefundImmediateRequest", targetNamespace = "http://www.etisalat.billingadapter.ae/1.0")
        ae.billingadapter.etisalat._1.RefundImmediatelyRequest refundImmediateRequest
    );
}
